-- Sample data for reuse POS

INSERT INTO ITEM_CATEGORY (NAME, DESCRIPTION) VALUES ('ブランド品', 'ブランドバッグ・財布・アクセサリー');
INSERT INTO ITEM_CATEGORY (NAME, DESCRIPTION) VALUES ('トレカ', 'トレーディングカード・TCG');
INSERT INTO ITEM_CATEGORY (NAME, DESCRIPTION) VALUES ('ゲーム', 'ゲームソフト・ハード');
INSERT INTO ITEM_CATEGORY (NAME, DESCRIPTION) VALUES ('家電', '生活家電・デジタル家電');
INSERT INTO ITEM_CATEGORY (NAME, DESCRIPTION) VALUES ('貴金属', '金・銀・プラチナ・宝石');

INSERT INTO BUYBACK_ITEM (ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME)
VALUES ('BRD-20260401-001', 'ルイヴィトン モノグラム ネヴァーフル MM', 1, 85000, 128000, 'A', 'ON_DISPLAY', '田中太郎');

INSERT INTO BUYBACK_ITEM (ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME)
VALUES ('TRC-20260401-001', 'ポケモンカード リザードンex SAR', 2, 12000, 18000, 'S', 'IN_STOCK', '佐藤花子');

INSERT INTO BUYBACK_ITEM (ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME)
VALUES ('GAM-20260402-001', 'Nintendo Switch 有機ELモデル', 3, 22000, 32000, 'B', 'ON_DISPLAY', '鈴木一郎');

INSERT INTO BUYBACK_ITEM (ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME)
VALUES ('GLD-20260403-001', 'K18 ネックレス 45cm 10g', 5, 95000, 120000, 'A', 'SOLD', '高橋美咲');
