-- Sample data for reuse POS (MERGE to avoid duplicate key on test context reload)

MERGE INTO ITEM_CATEGORY (ID, NAME, DESCRIPTION) KEY(ID) VALUES (1, 'ブランド品', 'ブランドバッグ・財布・アクセサリー');
MERGE INTO ITEM_CATEGORY (ID, NAME, DESCRIPTION) KEY(ID) VALUES (2, 'トレカ', 'トレーディングカード・TCG');
MERGE INTO ITEM_CATEGORY (ID, NAME, DESCRIPTION) KEY(ID) VALUES (3, 'ゲーム', 'ゲームソフト・ハード');
MERGE INTO ITEM_CATEGORY (ID, NAME, DESCRIPTION) KEY(ID) VALUES (4, '家電', '生活家電・デジタル家電');
MERGE INTO ITEM_CATEGORY (ID, NAME, DESCRIPTION) KEY(ID) VALUES (5, '貴金属', '金・銀・プラチナ・宝石');

MERGE INTO BUYBACK_ITEM (ID, ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME) KEY(ID)
VALUES (1, 'BRD-20260401-001', 'ルイヴィトン モノグラム ネヴァーフル MM', 1, 85000, 128000, 'A', 'ON_DISPLAY', '田中太郎');

MERGE INTO BUYBACK_ITEM (ID, ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME) KEY(ID)
VALUES (2, 'TRC-20260401-001', 'ポケモンカード リザードンex SAR', 2, 12000, 18000, 'S', 'IN_STOCK', '佐藤花子');

MERGE INTO BUYBACK_ITEM (ID, ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME) KEY(ID)
VALUES (3, 'GAM-20260402-001', 'Nintendo Switch 有機ELモデル', 3, 22000, 32000, 'B', 'ON_DISPLAY', '鈴木一郎');

MERGE INTO BUYBACK_ITEM (ID, ITEM_CODE, NAME, CATEGORY_ID, PURCHASE_PRICE, SELLING_PRICE, ITEM_CONDITION, STATUS, CUSTOMER_NAME) KEY(ID)
VALUES (4, 'GLD-20260403-001', 'K18 ネックレス 45cm 10g', 5, 95000, 120000, 'A', 'SOLD', '高橋美咲');

-- Reset identity sequences to avoid collision with test-generated rows
ALTER TABLE ITEM_CATEGORY ALTER COLUMN ID RESTART WITH 100;
ALTER TABLE BUYBACK_ITEM ALTER COLUMN ID RESTART WITH 100;
